[web]
54.164.148.141 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/voting-app-key

[data]
3.92.222.96 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/voting-app-key

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
